#.DE
Allgemein
	3SAT
	ARD-ALPHA
	ARTE
	DAS ERSTE
	HR-FERNSEHEN
	MDR FERNSEHEN SACHSEN
	MDR FERNSEHEN SACHSEN-ANHALT
	MDR FERNSEHEN THÜRINGEN
	NDR FERNSEHEN INTERNATIONAL
	NDR HAMBURG
	NDR MECKLENBURG-VORPOMMERN
	NDR NIEDERSACHSEN
	NDR SCHLESWIG-HOLSTEIN
	ONE ADRIA
	PHOENIX
	PROSIEBEN
	PROSIEBEN MAXX
	RADIO BREMEN FERNSEHEN
	RBB BERLIN
	RBB BRANDENBURG
	SR FERNSEHEN
	SRF
	SWR FERNSEHEN BADEN-WÜRTTEMBERG
	SWR FERNSEHEN RHEINLAND-PFALZ
	SUPER RTL
	WDR FERNSEHEN
	ZDF
	ZDFINFO
	ZDFNEO
Nachrichten
	DW ARABIC
	DW ENGLISH
	DW ESPANOL
	DW RUSSIAN
	NACHRICHTEN 360
	RT DE
	TAGESSCHAU 24
	WELT
	PARLAMENTSFERNSEHEN 1
	PARLAMENTSFERNSEHEN 2
	PARLAMENTSFERNSEHEN 3
	PARLAMENTSFERNSEHEN 4
Sport
	MORE THAN SPORTS TV
	MOTORVISION TV
	RAN1
	SPORTDIGITAL FUSSBALL
Musik
	DASDING 90.8
	DELUXE DANCE
	DELUXE LOUNGE
	DELUXE MUSIC
	DELUXE RAP
	DMF
	FOLX MUSIC
	MAGENTA MUSIK 360
	ONE1 MUSIC
	RADIO 21 TV
	ROCK ANTENNE
	ROCKLAND TV
	SONUS FM TV
	SWR 3 VISUAL RADIO
	UNSERDING
	VOLKSMUSIK TV
	WDR 1 LIVE
	ZWEI2 MUSIC
Kinder
	KIKA
	NICK GERMANY
	NICKELODEON
	NICKELODEON DEUTSCHLAND
Natur & Wissen
	ADVENTURE EARTH
	ANIMAL KINGDOM
	AUTENTIC HISTORY
	AUTENTIC TRAVEL
	DOKUSAT
	TERRA MATER WILD
	TERRA MATER WILD ENGLISH
	WELT DER WUNDER TV
Religion
	BIBEL TV
	BIBEL TV IMPULS
	BIBEL TV MUSIK
	HOPE CHANNEL GERMAN
	LIGHT CHANNEL
	SENDER NEU JERUSALEM
	SOPHIA TV
	SOPHIA TV ESPAÑOL
	SOPHIA TV FRANÇAIS
	SOPHIA TV ITALY
Shopping
	1-2-3 TV
	HSE
	HSE24 EXTRA
	HSE24 TREND
	ISTUFF
	JUWELO
	KAUFBEI TV
	QVC 2 GERMANY
	QVC GERMANY
	QVC STYLE GERMANY
	SONNENKLAR TV
Regional
	ALEX BERLIN
	ALLGÄU TV
	ALTENBURG TV
	AUGSBURG TV
	BADEN TV
	BADEN TV SÜD
	BLK REGIONAL TV
	BLK TV
	BLK TV HOHENMÖLSEN
	BR FERNSEHEN NORD
	CHEMNITZ FERNSEHEN
	CIRA TV
	DRESDEN FERNSEHEN
	ECHTJETZT TV
	EMS TV LINGEN
	ERZ-TV STOLLBERG
	EUROAL TV
	FILSTALWELLE
	FINEST TV
	FRANKEN FERNSEHEN
	FRANKENPLUS
	HAMBURG 1
	HANDYSTAR
	KANAL12 SPREMBERG TV
	KULTURMD
	L-TV
	LABOR14
	LAUSITZWELLE
	LEIPZIG FERNSEHEN
	MC TV
	MDF.1
	MÜNCHEN TV
	NIEDERBAYERN TV
	NIEDERBAYERN TV DEGGENDORF & STRAUBING
	NIEDERBAYERN TV LANDSHUT
	NIEDERBAYERN TV PASSAU
	NOA 4 HAMBURG
	NOA 4 NORDERSTEDT
	NRWISION
	OBERPFALZ TV
	OF-TV OFFENBACH
	OK4
	OK54
	OK DESSAU
	OK FLENSBURG
	OK KAISERSLAUTERN
	OK KASSEL
	OK KIEL
	OK MAGDEBURG
	OK MERSEBURG-QUERFURT
	OK RHEIN-MAIN
	OK SALZWEDEL
	OK STENDAL
	OK TRIER
	OK WEINSTRASSE
	OK WERNIGERODE
	OK-TV LUDWIGSHAFEN
	PUNKTUM FERNSEHEN
	RADIO WESER TV BREMEN
	RBW
	RBW BITTERFELD-WOLFEN
	REGIO TV BODENSEE
	REGIO TV SCHWABEN
	REGIO TV STUTTGART
	RENNSTEIG TV
	RFH
	RFO
	RIC
	RNF
	SAARLAND FERNSEHEN 1
	SAARLAND FERNSEHEN 2
	SACHSEN EINS
	SALVE TV
	SEENLUFT24
	STUDIO 47
	TELTOWKANAL
	TIDE TV
	TIVITÜRK
	TV38 SÜDOST-NIEDERSACHEN
	TV INGOLSTADT
	TV MAINFRANKEN
	TV OBERFRANKEN
	TVA
	WDR FERNSEHEN AACHEN
	WDR FERNSEHEN BIELEFELD
	WDR FERNSEHEN BONN
	WDR FERNSEHEN DORTMUND
	WDR FERNSEHEN DUISBURG
	WDR FERNSEHEN DÜSSELDORF
	WDR FERNSEHEN ESSEN
	WDR FERNSEHEN KÖLN
	WDR FERNSEHEN MÜNSTER
	WDR FERNSEHEN SIEGEN
	WDR FERNSEHEN WUPPERTAL
Sonstiges
	ANIXE +
	ANIXE HD SERIE
	ARISTO TV
	DA VINCI ASIA VIETNAM
	KABEL EINS DOKU
	RTL CRIME
	RTL PASSION