#.NL
Algemeen
	A1 TV
	AT5
	FEEL GOOD TV
	IDEAAL TV
	INFAST
	INTROUBLE
	INWONDER
	LINQ TV
	ML5 TV
	NOOS TV
	OPEN ROTTERDAM
	RTV 1
	SBS6 CLASSICS
	SIRIS TV
	ДОЖДЬ
Nieuws
	BNR NIEUWSRADIO
	DEN HAAG TV
	NH NIEWS
	TWEEDE KAMER: ACTUALITEITENKANAAL
	TWEEDE KAMER: ALETTA JACOBSZAAL
	TWEEDE KAMER: ENQUETEZAAL
	TWEEDE KAMER: GROEN VAN PRINSTERERZAAL
	TWEEDE KAMER: KLOMPEZAAL
	TWEEDE KAMER: MAX VAN DER STOELZAAL
	TWEEDE KAMER: PLENAIRE ZAAL
	TWEEDE KAMER: SUZE GROENEWEGZAAL
	TWEEDE KAMER: THORBECKEZAAL
	TWEEDE KAMER: TILANUSKAMER
	TWEEDE KAMER: TROELSTRAZAAL
	TWEEDE KAMER: WTTEWAALL VAN STOETWEGENZAAL
Muziek
	BE@TTV
	DEEPHOUSE DISTRICT
	FOMIXTV
	GIGANT FM
	HYPE VISUAL RADIO
	JIN TV
	LOE TV
	MAGIC POWERRADIO
	PODIUM.TV
	PODIUM.TV 2
	PODIUM.TV 3
	QMUSIC
	RADIO 10
	RADIO 350
	RADIO 538
	RADIO AALSMEER TV
	RADIO JND
	RADIO STAD DEN HAAG
	RADIONL TV
	RADIOTOPPERS
	RARARADIO
	ROTTERDAM PODIUM TV
	SALTO BRASA MUSIC
	XITE
	XITE HITS GERMANY
	XITE HITS UK
	XITE ROCK X METAL
	ZFM ZOETERMEER
Regionaal
	1ALMERE TV
	1TWENTE TV
	ALTENA TV
	ASSEN TV
	BR6 TV
	DIT IS HELMOND
	DTV DEN BOSCH
	DTV MAASHORST
	DTV OSS & BERNHEZE
	HAARLEM105 RTV
	HTR TV
	KEMPENTV
	L1MBURG TV
	LANGSTRAAT TV
	LANSINGERLAND TV
	LEO MIDDELSÉ TV
	LON TV
	LOZ
	MEER TV
	MERWE TV
	OMROEP BRABANT
	OMROEP BRABANT RADIO
	OMROEP CENTRAAL TV
	OMROEP DOMMELLAND
	OMROEP FLEVOLAND
	OMROEP GELDERLAND HD
	OMROEP HOEKSCHE WAARD
	OMROEP HULST TV
	OMROEP LAND VAN CUIJK
	OMROEP LINGEWAARD
	OMROEP MEIERIJSTAD
	OMROEP ONS WEST BRABANT
	OMROEP PEELRAND
	OMROEP SÚDWEST
	OMROEP TILBURG
	OMROEP TILBURG TV
	OMROEP VENLO
	OMROEP VENRAY
	OMROEP WEST
	OMROEP ZEELAND
	OMROP FRYSLÂN
	OOG TV
	ORTS
	REGIO90 TV
	REGIO TV DE BILT
	REGIO TV NIEUWS
	RN7 TV
	RPL TV WOERDEN
	RTV ARNHEM
	RTV DRENTHE
	RTV GO!
	RTV HORIZON
	RTV LOVE
	RTV MAASTRICHT
	RTV MEPPEL
	RTV NOF ACHTKARSPELEN & TYTSJERKSTERADIEL
	RTV NOORD
	RTV NOORD EXTRA
	RTV NOORDOOST FRIESLAND
	RTV NUNSPEET
	RTV OOST
	RTV PARKSTAD
	RTV PURMEREND
	RTV RIJNMOND
	RTV RIJNMOND EXTRA
	RTV RIJNSTREEK TV
	RTV SLOS
	RTV UTRECHT
	RTV VELUWEZOOM
	RTV WESTERWOLDE
	RTV ZULTHE
	SALTO 1
	SALTO 2
	SALTO 4
	SALTO ADE
	SALTO MALIVE
	SAMEN1 TV
	SCHIE TV
	SLEUTELSTAD TV
	SLOTSTAD TV
	SOL 2
	SRC TV
	STREEK TV
	STREEKSTAD ALKMAAR CENTRAAL
	STUDIO040 TV
	STUDIO RHEDEN
	TV ELLEF
	USTAD
	VECHTDAL TV
	WEEFF TV
	WEERTFM TV
	WOS TV
	XON
	ZO!34
